### ISSUE TITLE
udunits2 available for R version 3.3.2 on linux?

### ISSUE THREAD

**Issue by akitepowell** [pacificclimate/Rudunits2#11]
Hi,
We are having trouble installing udunits2 on R 3.3.2 using linux and using Rstudio server pro.  The message we get is the package is unavailable for this version of R.  Is this a known issue?  I don't have this issue on my local windows computer using the same version of R.  Any assistance would be very helpful.
Thanks,
Aaron

**Comment by jameshiebert** [comment]
It *should* be available. I'm not really familiar with package installation on Rstudio server pro. How does it differ from installing with ``install.packages()``? Can you provide any more information?
