### ISSUE TITLE
environment variable UDUNITS2_LIB/UDUNITS2_LIBS mismatch in configure

### ISSUE THREAD

**Issue by iynehz** [pacificclimate/Rudunits2#12]
It's mentioned in an error help message as UDUNITS2_LIB (without S)
https://github.com/pacificclimate/Rudunits2/blob/b108303acd4c3c0461ad9355774bc95016fe2d7e/configure.ac#L51

But when it's used, it's UDUNITS2_LIBS (with S)
https://github.com/pacificclimate/Rudunits2/blob/b108303acd4c3c0461ad9355774bc95016fe2d7e/configure.ac#L28

**Comment by jameshiebert** [comment]
Ah, you're right. Thanks for the catch!
