### ISSUE TITLE
Add /usr/include/udunits2 to list of locations searched for udunits2.h

### ISSUE THREAD

**Issue by gavinsimpson** [pacificclimate/Rudunits2#14]
On Fedora 25, the distro package udunits2-devel installs `udunits2.h` to `/usr/include/udunits2`. It would be most useful if the configure routine could also look in this location rather than having to remember to use `configure.args` when installing package via `install.packges()`.

**Comment by jameshiebert** [comment]
Yeah, it'd probably be useful to give the configure script a list of a few common install locations. Not a bad idea.

**Comment by wdkrnls** [comment]
Could the installation script also look for the recommended environment variables as well? I was able to install on CentOS6.6 using `configure.args`.

**Comment by jameshiebert** [comment]
@wdkrnls The configure script already incorporates information from a wide range of environment variables (`R_HOME`, `CFLAGS`, `CPPFLAGS`, `LIBS`, `UDUNITS2_INCLUDE`, `UDUNITS2_LIBS`). Which environment variables in particular are you referring to?

**Comment by harryprince** [comment]
When I install `sf` package, I got same error.

This works for me:

```
sudo yum install  udunits2-devel
```

```
install.packages("udunits2",configure.args='--with-udunits2-include=/usr/include/udunits2/')
```
