### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by HenrikBengtsson** [pacificclimate/Rudunits2#28]
@jameshiebert, is this repos / package still maintained?  Last CRAN update was Nov 2016.

I'm asking because Issue #25 causes lots of extra work to end-users but also sysadms around the world.  There should be a simple fix to it and if deployed and uploaded to CRAN there will be lots of hours and frustration saved every day.

If not maintained, maybe there are others who are willing to take over the maintenance of this package?

**Comment by jameshiebert** [comment]
Yes, it is. We're working on it, but multi-platform packaging is surely the bain of every developer's existence. Stand by; we're working on it.

**Comment by HenrikBengtsson** [comment]
Do you got an ETA for the fix?

**Comment by HenrikBengtsson** [comment]
If it's not clear, just fixing the bug so env var `UDUNITS2_INCLUDE` is recognized would go a long way.  Then sysadms could set this globally and `install.packages("udunits2")` would work out of the box - at least on CentOS but I suspect also on other distros.
